[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ugtext_processer"
version = "0.1.4"
authors = [
    { name = "uyplayer", email = "uyplayer@outlook.com" },
]
description = "text processing for uyghur script"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
]
dependencies = [
    "pytest",
    "epitran",
    "sentencepiece",
    "tokenizers"

]

[project.optional-dependencies]
test = [
    "pytest",
]


[tool.setuptools.packages.find]
where = ["ugtext_processer"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
